### PR TITLE
Handle and report invalid notify(err) argument. Fixes #110.

### LINKED ISSUE #110: Cannot read property 'stack' of null
Is `.notify` method designed to only accept instance of `Error` as first param?
If this method is called with `null` it fails with `Cannot read property 'stack' of null` exception.
I only discovered this after I experienced it on my production server. Not good.

I understand that the docs say the first param should be either Error object or String, but still I can't appreciate the **error reporting** library crashing my app when I call it with something unexpected.
Thanks.

### PR DESCRIPTION
**Pull request by bengourley**
`notify(err…)` now catches and reports the case where `err=null|undefined|0|true|false`.

An error-level log is printed and Error is constructed and sent to Bugsnag with the offending parameter. All of the arguments are captured and sent in the report's metadata too, to help provide context for when this happens.

### CODE REVIEW

**Comment by bengourley** [comment]
Some examples of this in use:

### Log output
image

### Dashboard
image

File: lib/bugsnag.js [hunk 1]
```diff
@@ -116,6 +116,21 @@ Bugsnag.notify = function(error, options, cb) {
     if (!options) {
         options = {};
     }
+    if (!error && typeof error !== "string") {
+        Configuration.logger.error("Bugsnag.notify(error…) accepts an object or a string but was called with '" + error + "'");
+        options.metaData = {
+            "notify() arguments":
+                JSON.stringify(
+                    [].map.call(arguments, function(arg) { return arg }),
+                    function replacer(key, value) {
```
Comment (bengourley) [inline lib/bugsnag.js]: I felt the need to implement this [custom replacer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#The_replacer_parameter) so that `undefined` and `Function` properties aren't misleadingly stripped/replaced with `null`.
